/*
 * This source file was generated by the Gradle 'init' task
 */
package question_2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MovieTicketsTest {
    @Test
    public void CalculateTotalTicketPrice_CalculatedSuccessFully() {
        MovieTickets moT = new MovieTickets("Damsel", 3, 100);
        double total = moT.CalculateTotalTicketPrice(3, 100);
        assertEquals(342.0, total, 0.001);
    }

    // Test valid name
    @Test
    public void testValidPrice_Valid() {
        MovieTickets moT = new MovieTickets("Damsel", 3, 100);
        assertTrue(moT.ValidateData());
    }
}
