/*
 * This source file was generated by the Gradle 'init' task
 */
package question_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MovieTicketsTest {
    @Test
    public void CalculateTotalSales_ReturnsExpectedTotalSales() {
        System.out.println("RepairCosts");
        int[] movieTicketSales = { 1000, 2000, 3000 };
        MovieTickets instance = new MovieTickets();
        double expResult = 6000;
        double result = instance.TotalMovieSales(movieTicketSales);
        assertEquals(expResult, result);
    }

    // testing top movie
    @Test
    public void TopMovieSales_ReturnsTopMovie() {
        System.out.println("TopTechnician");
        int[] movie = null;
        MovieTickets instance = new MovieTickets();
        int expResult = 0;
        int result = instance.TopMovie(movie);
        assertEquals(expResult, result);

    }
}
